package edu.uci.ics.chrisr6.service.basic.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;

@JsonIgnoreProperties(value = "dataValid") // Tells Jackson to ignore dataValid field generated by DataValidation interface
@JsonInclude(JsonInclude.Include.NON_NULL) // Tells Jackson to ignore all fields with value of NULL
public class SessionResponseModel extends GeneralResponseModel {

    String sessionID;

    public SessionResponseModel() {

    }

    public SessionResponseModel(int resultCode) {
        super(resultCode);
    }

    public SessionResponseModel(int resultCode, String sessionID) {
        super(resultCode);
        this.sessionID = sessionID;
    }

    public String getSessionID() {
        return sessionID;
    }

    public void setSessionID(String sessionID) {
        this.sessionID = sessionID;
    }
}
