/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.uci.ics.chrisr6.service.basic;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void firstTest() {
    }
}
